import type { Metadata } from "next";
import Nav from "./components/navbar";

import "./globals.css";

import { Inter } from 'next/font/google';
import Footer from "./components/footer";

const inter = Inter({ subsets: ['latin'] });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} `}
      >
       <Nav />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
