import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import {
  ClerkProvider,
  
} from '@clerk/nextjs'
import type { Metadata } from "next";
import Nav from "./components/navbar";

import "./globals.css";

import { Inter } from 'next/font/google';
import Footer from "./components/footer";

const inter = Inter({ subsets: ['latin'] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${inter.className} `}
      >
       <Nav />
      
       <ToastContainer position="top-right" autoClose={3000} hideProgressBar={true} />
        {children}
        <Footer/>
      </body>
    </html>
    </ClerkProvider>
  );
}
